### DISCUSSION TITLE
Simplify the monitor template

### DISCUSSION THREAD

**Discussion by tomorrowshipyltm** [apache/hertzbeat#2179] [Ideas]
Hello, community

**Background**

There is a lot of duplication in the monitoring templates. For example, in the app-centos.yml file, different metrics only differ in the script and parseType, while other parameters like host, port, and username are repeated. This leads to longer YAML files.

  ```
protocol: ssh
    ssh:
      host: ^_^host^_^
      port: ^_^port^_^
      username: ^_^username^_^
      password: ^_^password^_^
      privateKey: ^_^privateKey^_^
      timeout: ^_^timeout^_^
      reuseConnection: ^_^reuseConnection^_^
      script: free -m
      parseType: multiRow
```

      
**Suggestion**

Consider extracting the repetitive parameters into a commonParam section, for example

```
commonParam:
      host: ^_^host^_^
      port: ^_^port^_^
      username: ^_^username^_^
      password: ^_^password^_^
protocol: ssh
ssh:
  script : uname
  parseType: multiRow
```
