### DISCUSSION TITLE
请问一下要如何在 hertzbeat 中动调呢？

### DISCUSSION THREAD

**Discussion by Drun1baby** [apache/hertzbeat#2567] [Q&A]
我使用的是 docker-compose.yml 的启动方式，整个 yml 模板如下

```yaml
version: '3.8'

services:
  hertzbeat:
    image: apache/hertzbeat
    container_name: hertzbeat
    ports:
      - "1157:1157"
      - "1158:1158"
      - "5005:5005"
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    restart: always
```

但是启动动调失败了，请问一下你们方便帮忙看一下吗？

**Comment by Aias00** [comment]
hi, i started successfully. docker compose file like this :

i just add image tag directly

```
version: '3.8'

services:
  hertzbeat:
    image: apache/hertzbeat:v1.6.0
    container_name: hertzbeat
    ports:
      - "1157:1157"
      - "1158:1158"
      - "5005:5005"
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    restart: always
```

**Comment by Aias00** [comment]
if u use my compose file, still have failure, u can paste ur error logs here

**Reply by Drun1baby** [reply]
I failed 

<img width="867" alt="image" src="https://github.com/user-attachments/assets/90e439f9-930c-4c0f-8121-6b107c6722b0">

here is my configuration

<img width="909" alt="image" src="https://github.com/user-attachments/assets/2b47242c-2748-4486-a3f6-0544b8f319b7">

**Reply by Drun1baby** [reply]
And there is no -agentlib in the process

<img width="585" alt="image" src="https://github.com/user-attachments/assets/dac068d5-4cbf-4095-94d8-717221635c06">

**Reply by Aias00** [reply]
hi, I just start the docker container successfully.

**Reply by Drun1baby** [reply]
mac cause?

**Reply by Aias00** [reply]
I mean I never connect to the debugger port. i can try

**Reply by Drun1baby** [reply]
all right, I thought you had successfully debugged it

**Comment by Drun1baby** [comment]
I can also run successfully, but I am unable to perform JVM debugging

**Comment by Aias00** [comment]
hi, i submitted a pr, to support this custom java_opts

**Reply by Drun1baby** [reply]
this docker-compose.yml still failed

```yml
version: '3.8'

services:
  hertzbeat:
    image: apache/hertzbeat:v1.6.0
    container_name: hertzbeat
    ports:
      - "1157:1157"
      - "1158:1158"
      - "5005:5005"
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    restart: always
```
