### ISSUE TITLE
[Task] support the VictoriaMetrics cluster 

### ISSUE THREAD

**Issue by LHB6540** [apache/hertzbeat#1771]
### Question

我的VictoriaMetrics是集群模式部署的，对外暴露的接口为
写接口：http://172.19.0.2:8480/insert/<租户ID>/
查接口：http://172.19.0.2:8481/select/<租户ID>/
请问如何在配置文件中填写时序库地址

``` yaml
# 存储历史数据方式, 下方只能enabled启用一种方式
    jpa:
      enabled: false
      expire-time: 1h
    victoria-metrics:
      enabled: true
      url: http://172.19.0.2:8480/insert/0/prometheus
      username: 
      password:
```
