### ISSUE TITLE
[BUG] snmp interface speed unit conversion

### ISSUE THREAD

**Issue by zxp** [apache/hertzbeat#1775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

currently in app-*_switch.yml defined interface speed is `- speed=ifSpeed / 1024 / 1024`, where ifSpeed unit is bit/sec, when convert to MB/s should first devide by 8. 

### Expected Behavior

`- speed=ifSpeed / 8 / 1024 / 1024`

### Environment

```markdown
HertzBeat version(s): v1.5.0
```

**Comment by tomsun28** [comment]
hi, can you help us fix it?

**Comment by tomsun28** [comment]
welcome to try submit the pr, everything has the first time.  the snmp operation support `get` or `walk`

```
      community: ^_^community^_^
      # snmp version
      version: ^_^version^_^
      # snmp operation: get, walk
      operation: get
      # metrics oids: metric_name - oid_value
      oids:
        name: 1.3.6.1.2.1.1.5.0
        descr: 1.3.6.1.2.1.1.1.0
        uptime: 1.3.6.1.2.1.1.3.0
        location: 1.3.6.1.2.1.1.6.0
        contact: 1.3.6.1.2.1.1.4.0
```
