### ISSUE TITLE
[Question] aws ses setup

### ISSUE THREAD

**Issue by martinblascop** [apache/hertzbeat#2728]
### Question

Hi, I cannot send emails. It appears to be that the [mail from address is getting its value from the username](https://github.com/apache/hertzbeat/blob/febc911639a2692791faac5b0f4bef57195bba83/manager/src/main/java/org/apache/hertzbeat/manager/component/alerter/impl/EmailAlertNotifyHandlerImpl.java#L125)
In my setup with aws ses I have

```yaml
mail:
  username: <access_key_id>
  password: <secret_access_key>
```
Thus I'm getting an error because I cannot set another value to a mail from address like `myemail@mydomain.com`
