### ISSUE TITLE
[BUG] <title>After running for a period of time, the history chart of custom monitoring will freeze and the browser will crash without error logs

### ISSUE THREAD

**Issue by liu304424818** [apache/hertzbeat#3262]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

docker-compose  pg+vict部署方式  

自定义监控 运行一段时间后 历史图表会卡死浏览器崩溃 没有报错日志 我和我同事都有这个现象  必现

docker-compose pg+vict configuration method

After running the custom monitoring for a period of time, the historical chart will freeze and the browser will crash without error logs. My colleagues and I have this phenomenon.

![Image](https://github.com/user-attachments/assets/9619c5b7-44d7-4712-8e3f-688fb2c72dab)

### Environment

```markdown
HertzBeat version(s):1.7
```

**Comment by liu304424818** [comment]
必现的 不是偶现  前段请求 cpu显示接口pending

**Comment by liu304424818** [comment]
我的自定义监控 完全复制了ubuntu的系统监控  然后我再里面加了两个

- name: sda_mountPath
 i18n:
 zh-CN: sda挂载路径
 en-US: sdaMountPath
 priority: 3
 fields:
 - field: sdaMounted
 type: 0
 unit: "/mnt/ssd"
 i18n:
 zh-CN: sda挂载点
 en-US: sdaMounted
 protocol: ssh
 ssh:
 host: ^_^host^_^
 port: ^_^port^_^
 username: ^_^username^_^
 password: ^_^password^_^
 privateKey: ^_^privateKey^_^
 privateKeyPassphrase: ^_^privateKeyPassphrase^_^
 timeout: ^_^timeout^_^
 reuseConnection: ^_^reuseConnection^_^
 # whether to use proxy server for ssh connection
 useProxy: ^_^useProxy^_^
 # ssh proxy host: ipv4 domain
 proxyHost: ^_^proxyHost^_^
 # ssh proxy port
 proxyPort: ^_^proxyPort^_^
 # ssh proxy username
 proxyUsername: ^_^proxyUsername^_^
 # ssh proxy password
 proxyPassword: ^_^proxyPassword^_^
 # ssh proxy private key
 proxyPrivateKey: ^_^proxyPrivateKey^_^
 script: if [[ -n "$(lsblk | grep /mnt/ssd | awk '{print $NF}')" && "$(lsblk | grep /mnt/ssd | awk '{print $NF}')" = '/mnt/ssd' ]]; then echo 1; else echo 0; fi
 parseType: oneRow

- name: version
 i18n:
 zh-CN: 版本号
 en-US: version info
 priority: 3
 fields:
 - field: who
 type: 1
 label: true
 i18n:
 zh-CN: 板子
 en-US: who
 - field: bundle
 type: 0
 i18n:
 zh-CN: bundle版本
 en-US: bundle
 protocol: ssh
 ssh:
 host: ^_^host^_^
 port: ^_^port^_^
 username: ^_^username^_^
 password: ^_^password^_^
 privateKey: ^_^privateKey^_^
 privateKeyPassphrase: ^_^privateKeyPassphrase^_^
 timeout: ^_^timeout^_^
 reuseConnection: ^_^reuseConnection^_^
 # whether to use proxy server for ssh connection
 useProxy: ^_^useProxy^_^
 # ssh proxy host: ipv4 domain
 proxyHost: ^_^proxyHost^_^
 # ssh proxy port
 proxyPort: ^_^proxyPort^_^
 # ssh proxy username
 proxyUsername: ^_^proxyUsername^_^
 # ssh proxy password
 proxyPassword: ^_^proxyPassword^_^
 # ssh proxy private key
 proxyPrivateKey: ^_^proxyPrivateKey^_^
 script: version|grep app_uuid | awk -F'"' 'BEGIN{print "who bundle"} {for(i=1;i<=NF;i++)if($i~/app_uuid/){printf NR==1?"A %s\n":"B %s\n",$4;break}}'
 parseType: multiRow

**Comment by liu304424818** [comment]
我的自定义监控完全copy了ubuntu系统监控之后  下面是我新增的

```yaml
- name: sda_mountPath
 i18n:
 zh-CN: sda挂载路径
 en-US: sdaMountPath
 priority: 3
 fields:
 - field: sdaMounted
 type: 0
 unit: "/mnt/ssd"
 i18n:
 zh-CN: sda挂载点
 en-US: sdaMounted
 protocol: ssh
 ssh:
 host: ^_^host^_^
 port: ^_^port^_^
 username: ^_^username^_^
 password: ^_^password^_^
 privateKey: ^_^privateKey^_^
 privateKeyPassphrase: ^_^privateKeyPassphrase^_^
 timeout: ^_^timeout^_^
 reuseConnection: ^_^reuseConnection^_^
 # whether to use proxy server for ssh connection
 useProxy: ^_^useProxy^_^
 # ssh proxy host: ipv4 domain
 proxyHost: ^_^proxyHost^_^
 # ssh proxy port
 proxyPort: ^_^proxyPort^_^
 # ssh proxy username
 proxyUsername: ^_^proxyUsername^_^
 # ssh proxy password
 proxyPassword: ^_^proxyPassword^_^
 # ssh proxy private key
 proxyPrivateKey: ^_^proxyPrivateKey^_^
 script: if [[ -n "$(lsblk | grep /mnt/ssd | awk '{print $NF}')" && "$(lsblk | grep /mnt/ssd | awk '{print $NF}')" = '/mnt/ssd' ]]; then echo 1; else echo 0; fi
 parseType: oneRow
- name: version
 i18n:
 zh-CN: 版本号
 en-US: version info
 priority: 3
 fields:
 - field: who
 type: 1
 label: true
 i18n:
 zh-CN: 板子
 en-US: who
 - field: bundle
 type: 0
 i18n:
 zh-CN: bundle版本
 en-US: bundle
 protocol: ssh
 ssh:
 host: ^_^host^_^
 port: ^_^port^_^
 username: ^_^username^_^
 password: ^_^password^_^
 privateKey: ^_^privateKey^_^
 privateKeyPassphrase: ^_^privateKeyPassphrase^_^
 timeout: ^_^timeout^_^
 reuseConnection: ^_^reuseConnection^_^
 # whether to use proxy server for ssh connection
 useProxy: ^_^useProxy^_^
 # ssh proxy host: ipv4 domain
 proxyHost: ^_^proxyHost^_^
 # ssh proxy port
 proxyPort: ^_^proxyPort^_^
 # ssh proxy username
 proxyUsername: ^_^proxyUsername^_^
 # ssh proxy password
 proxyPassword: ^_^proxyPassword^_^
 # ssh proxy private key
 proxyPrivateKey: ^_^proxyPrivateKey^_^
 script: version|grep app_uuid | awk -F'"' 'BEGIN{print "who bundle"} {for(i=1;i<=NF;i++)if($i~/app_uuid/){printf NR==1?"A %s\n":"B %s\n",$4;break}}'
 parseType: multiRow
```
