### ISSUE TITLE
[Question] Optimize the way of Dead Link Check

### ISSUE THREAD

**Issue by Cyanty** [apache/hertzbeat#3301]
### Question

Is it possible to use `tj-actions/changed-files` to optimize the Dead Link Check in the doc CI?
```yml
      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
        with:
          files: |
            **/*.md

      - name: Dead Link Check
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
        run: |
          sudo npm install -g markdown-link-check@3.8.7
          for file in ${ALL_CHANGED_FILES}; do
            if ! grep -Fxq "$file" ./script/ci/exclude_files.txt; then
              markdown-link-check -c ./script/ci/link_check.json -q "$file"
            fi
          done
```

Reference document: https://github.com/tj-actions/changed-files?tab=readme-ov-file
