### ISSUE TITLE
snmp结果需要做值映射转换

### ISSUE THREAD

**Issue by bestsiyue** [apache/hertzbeat#3384]
### Question

![Image](https://github.com/user-attachments/assets/43b6b7f0-7662-4a21-a272-ae2ae0914577)

![Image](https://github.com/user-attachments/assets/dfc17853-9e71-4429-80cd-e6e657037dae)

目前使用snmp获取的值，尤其是状态类的值，基本都以数字结果呈现。这样在展示时并不能很好的看到真实的状态。我也搜索过相关issue，目前并没有很好的解决办法。或许可以参考zabbix的实现逻辑，在模板中添加一个mapping配置项，在mapping中列举数字的映射关系，这样可以很好的展示想要的结果。

**Comment by tomsun28** [comment]
+1 good ideas, but the mapping logic we need design carefully.

**Comment by bestsiyue** [comment]
> 嗨，是否可以使用现有的 ，它是基于 Below的？`calculates``JexlExpression`
> 
> ```
> valueString = (value == 1 ? "Normal" : (value == 2 ? "Warning" : "Critical"));
> ```
> 
> 请参阅 ： https://hertzbeat.apache.org/zh-cn/docs/advanced/extend-http-default

hi,我参考了你的示例文档，文档中更多的是对于json结果的获取，snmp结果与json返回值有明显区别。

或许snmp的mappings可以这么设计？

`
    # (optional)metrics field alias name, it is used as an alias field to map and convert the collected data and metrics field
    aliasFields:
      - memoryDeviceIndex
      - memoryDeviceManufacturerName
      - memoryDeviceStatus
      - memoryDeviceLocationName
      - memoryDeviceSpeed
      - memoryDeviceSize

    mappings:
        memoryDeviceStatus: [1: "ABSENT", 2: "OK", 3: "WARNING", 4: "CRITICAL"]


    # mapping and conversion expressions, use these and aliasField above to calculate metrics value
    # eg: cores=core1+core2, usage=usage, waitTime=allTime-runningTime
    calculates:
      - Index=memoryDeviceIndex
      - ManufacturerName=memoryDeviceManufacturerName
      - Status=memoryDeviceStatus
      - LocationName=memoryDeviceLocationName
      - Speed=memoryDeviceSpeed
      - Size=memoryDeviceSize / 1024 / 1024
`

**Comment by bigcyy** [comment]
At the protocol level, the collected metrics are mapped to aliasField - value, and then further processed using a calculation expression to produce realField - realValue. If I understood the code correctly, I hope this is helpful to you.

```
fields:
  - field: my_status
    type: 1
    i18n:
      zh-CN: 状态
      en-US: Status

aliasFields:
  - memoryDeviceStatus

calculates:
  - Status = (memoryDeviceStatus == 1 ? "ABSENT" : (memoryDeviceStatus == 2 ? "OK" : (memoryDeviceStatus == 3 ? "WARNING" : "CRITICAL")))
```
refer to: 
- [SnmpCollectImpl.java](https://github.com/apache/hertzbeat/blob/master/hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/snmp/SnmpCollectImpl.java)
- [MetricsCollect.java calculateFields](https://github.com/apache/hertzbeat/blob/master/hertzbeat-collector/hertzbeat-collector-collector/src/main/java/org/apache/hertzbeat/collector/dispatch/MetricsCollect.java)
