### ISSUE TITLE
[BUG] <Grafana面板>Grafana面板访问链接为127.0.0.1:3000

### ISSUE THREAD

**Issue by love01211** [apache/hertzbeat#3459]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

按照文档新建一个Prometheus任务的监控，尝试复现使用Grafana可视化，遇到报错

![Image](https://github.com/user-attachments/assets/027cdbb7-9be7-4c75-b5f9-f9276654bc67)

官方文档
https://hertzbeat.apache.org/zh-cn/docs/help/grafana_dashboard

### Expected Behavior

我希望可以通过配置Grafana Url，让访问的url路径为指定的IP+port的方式，而是不是固定的127.0.0.1:3000/uri

### Steps To Reproduce

1. application.yml配置如下
```yml
grafana:
  enabled: true
  url: http://192.168.114.114:13000
  username: admin
  password: admin
```
2. docker-compose.yaml新增以下配置
```yml
  grafana:
    image: grafana/grafana:latest
    container_name: compose-grafana
    hostname: grafana
    restart: always
    environment:
      TZ: Asia/Shanghai
      LANG: zh_CN.UTF-8
      GF_AUTH_PROXY_ENABLED: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_USERS_VIEWERS_CAN_EDIT: true
      GF_SECURITY_ALLOW_EMBEDDING: true
    volumes:
      - ./gdata:/var/lib/grafana
    ports:
      - "13000:3000"
    networks:
      - hertzbeat
```
### Environment

```markdown
HertzBeat version(s):1.7.1
docker-compose: hertzbeat-postgresql-victoria-metrics
```
